happo/happo-e2e

.eslintignore, controller.js, src/createAssetPackage.js
This commit fixes two things:
- When svg images are part of an asset package, the hash url needs to
have a file suffix for Happo to show it
- Dynamic asset paths (i.e. containing query params) weren't injected in
the DOM snapshot html correctly.
The former issue I fixed by mapping the fetched content type to a file
suffix. This is for svg files mainly but I thought it would be to have
all images get the suffix.
The latter issue was fixed by ampersanding "&" before injecting the new
url in the html.
=> Make dynamic svg images appear in screenshots

controller.js, package.json, yarn.lock
Before, the only way you could upload images was via a path to a file in
the file system. When exploring Appium integrations
(https://github.com/happo/happo-appium) I noticed that we get base64
encoded buffers instead. So to avoid having to save a buffer to file
first, I'm making registerLocalSnapshot and uploadImage work with
buffers as well.
If the width and height is provided and you provide a buffer, we will
now also compute the dimensions on the fly for you.
=> Add support for buffer images

controller.js
If a test file ends up not recording any snapshots, we were still
sending an empty snap-request to happo. Since snap-request payloads are
basically black boxes to Happo's API, we need to avoid flooding it with
requests that end up being empty anyway.
=> Skip sending empty snap-requests to happo.io

takeDOMSnapshot.js
Fixes https://github.com/happo/happo-cypress/issues/98
If you navigate to a domain other than the original during a test, happo would throw an error:
Blocked a frame with origin ... from accessing a cross-origin frame
We can't do much about this error, so I'm simply ignoring it.
=> Ignore cross-origin errors in takeDOMSnapshot.init

src/resolveEnvironment.js, test/resolveEnvironment-test.js
This environment variable can be used to resolve the previous/before sha from git tags. If e.g. HAPPO_BEFORE_SHA_TAG_MATCHER=happo-*, the before sha will be resolved to the commit sha of a previous commit that has a happo-<something> tag present.
The current commit is ignored when resolving the previous sha. This way we can retrigger a run for a build that includes tagging the current commit, without causing it to compare with itself.
=> Add support for HAPPO_BEFORE_SHA_TAG_MATCHER

controller.js
We're trying to debug a bad looking screenshot and the baseUrl can help us out here.
=> Add baseUrl to console.log when css file fails to download

takeDOMSnapshot.js
the getElementAssetUrls can in some cases modify the DOM. If we record the html before calling getElementAssetUrls the modifications done are lost.
Modifications can happen for inlined canvases, as it does in the default handleBase64Image.
=> Handle asset urls before recording outer html

takeDOMSnapshot.js, test/takeDOMSnapshot-test.js
This commit addresses an issue where all elements matching a selector should be included in a screenshot. Specifically, this time it's a header where certain elements are rendered in a "portal" outside of some element. By allowing a new option passed in happo-cypress, "includeAllElements: true", we can send an array of elements to happo-e2e, and takeDOMSnapshot.js will then combine html for all matches in a single "package".
=> Allow multiple elements in takeDOMSnapshot.js

src/resolveEnvironment.js, test/github_merge_group_event.json, test/resolveEnvironment-test.js
This fixes a bug where the Happo status wouldn't be updated for a commit that was in a merge queue. We mainly need to resolve the base sha in order to get the status check posted.
=> Handle merge_group events in resolveEnvironment.js

src/makeAbsolute.js, test/makeAbsolute-test.js
We found this from a playwright test suite. An image with path ./image.jpg on an element with baseURI
http://localhost:3000/iframe.html would try to download the image from http://localhost:3000/iframe.html?/./image.jpg
We can fix this by making better use of the URL class in node.
=> Fix making relative url paths absolute

bin/happo-e2e.js, package.json, yarn.lock
The happo server now has support for a `skippedExamples` parameter to the call to finalize an async report. We can make use of that in a --skippedExample argument/option sent to the CLI.
Fixes #21
=> Add support for `--skippedExamples` sent in finalize call

controller.js
This function will be used by happo-cypress to clean up after a retried spec. In Cypress 12 and earlier, we were able to the the start and end of the failed attempt but in Cypress 13 we only get the timestamp for the whole spec execution (including failed attempt + retry). To make the cleanup process simpler, I'm adding a utility function to remove duplicates happening in a specific timeframe.
=> Add controller.removeDuplicatesInTimeframe function

takeDOMSnapshot.js, test/createAssetPackage-test.js, test/takeDOMSnapshot-test.js
In SVG elements, you can use <image href=""></image> to include a different image inside the svg. We weren't grabbing asset urls from these elements which led to broken images being displayed in Happo screenshots.
=> Grab asset urls from <image> tags as well

takeDOMSnapshot.js, test/takeDOMSnapshot-test.js
We noticed an issue with radio buttons and Cypress tests. The state of which ones were checked wasn't represented in the screenshot. We can improve this by recording the "checked" attribute based on the current value.
=> Register what radio buttons and checkboxes were checked

takeDOMSnapshot.js, test/takeDOMSnapshot-test.js
I noticed that in the browser, calling `element.href` can return the whole URL, including the base URL. For something like
<link href="../foo/bar.css"/>
this can fix certain issues since the baseURL is resolved automatically by the browser. We will get something like
'https://domain.com/foo/bar.css'
back if the page we are on is https://domain.com/hello/ladies.
=> Pick stylesheet href from property

.github/workflows/run-tests.yaml, controller.js, package.json, run-tests.sh, src/createAssetPackage.js, src/fetch.js, yarn.lock
We are seeing some ECONNRESET errors that seem to be happening when we are fetching CSS assets. Currently this causes the job to fail, but I am hoping we can smooth over this by adding some retries. Network flake is inevitable.
This also moves the `res.ok` handling into the fetch function, which allows us to clean up some other code a bit.
This is similar to how we have makeRequest structured in the happo.io package:
https://github.com/happo/happo.io/blob/74b23bf4/src/makeRequest.js
***
Only request 5 CSS files at a time
We are seeing some ECONNERESET errors when downloading a bunch of CSS
files. My current theory is that since we are requesting them all at the
same time, the 6th request is being immediately rejected. I am hoping to
stabilize this by controlling the concurrency here.
=> Retry fetch requests, control concurrency in CSS downloads

bin/happo-e2e.js
We noticed that these are on the comparisons but not the reports. Hoping to make the reports a little more useful by passing these through.
=> Pass link and message through when creating reports

.npmignore
WHen I published v2.6.2 I noticed that the test-images directory was included in the package, which makes the package much larger than it needs to be. Adding it to the ignore list along with an eslint file that also does not need to be distributed.
=> Ignore test-images and .eslintignore when publishing this package

src/resolveEnvironment.js
This has been the default on GitHub for new repos for a while now, and many repos have switched over to using main. I think we should switch in this repo as well.
This is a breaking change.
Addresses HAP-142
=> Fall back to origin/main instead of origin/master

test/resolveEnvironment-test.js
We recently renamed the default branch from master to main, and so we need to adjust our tests a bit.
=> Fix test for main branch rename

src/createAssetPackage.js
I noticed that our test for this function was flaky. I believe this is because we were adding items to the archive in our Promise.all, which could cause items to be added in an inconsistent order. We really want this to be built deterministically, so I am splitting it out so that we fetch the items in parallel and then follow up with adding them to the archive serially. This should probuce a more stable output.
=> Add items to archive serially when creating asset packages

playwright-tests/takeDOMSnapshot.test.js, playwright-tests/test-assets/svg-sprites/index.html, takeDOMSnapshot.js
When a page uses `<use>` elements referencing svg snippets defined elsewere on the page, we weren't including the source `<symbol>`s. By always injecting html for all svgs that define the `<symbol>` element, I think we can get these svgs to appear correctly in the screenshots, even when the svgs are defined outside of the element currently beeing screenshot.
=> Always include svgs with <symbol> elements

src/resolveEnvironment.js, test/resolveEnvironment-test.js
The error message here was a bit cryptic:
```
Error: Cannot find module '/path/to/some/file.json'
Require stack:
- /e2e/node_modules/happo-e2e/src/resolveEnvironment.js
...
```
I want to make it easier for people to troubleshoot this on their own. I think we can try/catch the require and provide a clearer error message that helps people understand that something may be up with the GITHUB_EVENT_PATH environment variable.
=> Improve error message when unable to resolve GITHUB_EVENT_PATH

playwright-tests/takeDOMSnapshot.test.js, takeDOMSnapshot.js
This option will change the behavior of the DOM snapshot. Instead of only including the element in the resulting html `strategy: 'clip'` will include the entire body, but will leave a data attribute in the DOM for the element under test.
Happo workers will honor this attribute and clip the screenshot on that element.
=> Add support for `strategy: 'clip'` for takeDOMSnapshot

controller.js, package.json, yarn.lock
Node v10 added the recursive option to mkdir, so I think we can safely remove this dependency now.
=> Remove mkdirp dependency

package.json, src/makeExternalUrlsAbsolute.js, yarn.lock
This has been supported by browsers for a while now, so I think we can remove this dependency without any trouble.
=> Remove string.prototype.replaceall dependency

test/controller-test.js, test/createAssetPackage-test.js, test/findCSSAssetUrls-test.js, test/makeAbsolute-test.js, test/makeExternalUrlsAbsolute-test.js, test/resolveEnvironment-test.js, test/takeDOMSnapshot-test.js
This reverts commit ef16a56e5c46ac607195fe8ced4e55259bafc7db.
I had misinterpreted a failure and removed these describes. It turns out that I was wrong, and we can use them after all! https://github.com/happo/happo-e2e/pull/59#issuecomment-2631231001
Thanks @cjihrig!
=> Revert "Remove describe from tests"

.eslintrc.js, playwright-tests/takeDOMSnapshot.test.js, playwright-tests/test-assets/style-collection/index.html, playwright-tests/test-assets/style-collection/index.js, takeDOMSnapshot.js
This will fix a bug where our style collection would not work if the stylesheet was using this pattern:
font: var(--some-var);
font-weight: var(--some-other-var);
Iterating over cssRules here would mean we collected styles that looked something like:
font-style: ;
font-variant-ligatures: ;
font-variant-caps: ;
font-variant-numeric: ;
font-variant-east-asian: ;
font-variant-alternates: ;
font-variant-position: ;
font-variant-emoji: ;
font-stretch: ;
font-size: ;
line-height: ;
font-family: ;
font-optical-sizing: ;
font-size-adjust: ;
font-kerning: ;
font-feature-settings: ;
font-variation-settings: ;
font-weight: var(--some-other-var);
Notice how properties are expanded and left with no content.
To fix this, we can use `textContent` of the style element instead. And if that isn't …
=> Use textContent of stylesheet if available

controller.js, run-tests.sh, test/controller-test.js
I wanted to run the controller test on its own, but it failed because
these env vars were set in the shell script. I started by adding a
setup.js file and importing it in all of the tests but then I realized
that we only need to do this in the controller test so I moved it there.
To make this work, we need to read the env vars lazily and not in the
module scope, so I did some light refactoring as well.
I had started to convert the tests to ESM but that ended up being a
rabbit hole of sorts and not something I need to do right now.
=> Localize test setup

controller.js, src/createAssetPackage.js, test/controller-test.js
When there are external assets at the same time as CSS files that fail to download, the CSS file will have an undefined `.css` property. We did not guard against that here, so people in this scenario ended up running into an unhandled error.
To fix this, we just need to guard against block.css being undefined.
I was able to reproduce this in our test suite and verified that it fixes the bug.
Fixes #58
=> Handle broken CSS files when there are external assets

bin/happo-e2e.js, controller.js, package.json, yarn.lock
We use this package outside of dev-only code, so it should be in dependencies. We also made some changes in v12 that we need to update for here.
=> Move happo.io from devDependencies to dependencies, update for v12

package.json, test/createAssetPackage-test.js, yarn.lock
This gives us more confidence that this function will continue to do the
correct thing.
I wanted to get this in before I refactor the function a bit.
=> Assert asset package contents in createAssetPackage test

package.json, src/createAssetPackage.js, test/createAssetPackage-test.js
This is how we create archives elsewhere, so we might as well build on top of it.
One improvement with this method is it enables zlib compression at level 6, which in my tests seems to reduce the size of asset packages by about 14%. That is one reach the package hash in the tests changed.
=> Refactor createAssetPackage to use happo.io's deterministicArchive

controller.js
We have been making some improvments in the core happo.io package to how assets are uploaded. To ensure that happo-e2e consumers benefit from these improvments, I am refactoring the controller to use the uploadAssets function from that package. This also gives us a little less code to maintain here, which is nice.
=> Refactor controller to use uploadAssets from happo.io package

package.json
We only run tests against Node 18+ in this repo, so I think it is safe to say that we only support Node 18+ here. This package also consumes happo.io which also only supports Node 18+.
=> Add engines property to package.json

.npmignore
I found that we might publish files here by running:
```sh
npm pack --dry-run
```
=> Add test-results to .npmignore

bin/happo-e2e.js
This will fix a bug where `import` is not valid syntax in CommonJS. Obviously we could benefit from better test coverage here. I'll follow up with that soon.
=> Import postGithubComment from build, not src

bin/happo-e2e.js, test/happo-e2e-test.js
We recently shipped a bug with an incorrect import statement. This should have been caught by any test running on this file but we did not have any.
I am getting the ball rolling here by writing a very basic test on this file. To make this bin script importable and executable as a function, I am doing some light refactoring at the same time.
We should definitely come back and add more testing, but for now this is a great improvement.
=> Add first test for bin/happo-e2e.js

playwright-tests/takeDOMSnapshot.test.js, playwright-tests/test-assets/constructed-styles/index.js, src/applyConstructedStylesPatch.js, takeDOMSnapshot.js
We know that using shorthand values with variables can lead to issues with the DOM snapshot. For instance,
p {
font: var(--font);
font-weight: var(--font-weight);
}
becomes
p {
font-family: ;
font-weight: ;
font-size: ;
... etc
}
See:
https://issues.chromium.org/issues/40905071#comment7 https://issues.chromium.org/issues/40240778#comment5
We can fix this by monkey-patching CSSStyleSheet and its functions. By recording the strings exactly as they are injected, we can preserve the "real" css that the user intended to apply.
=> Add monkey-patch for constructed styles

.eslintrc.js, src/applyConstructedStylesPatch.js, takeDOMSnapshot.js
We want this patch to work in Cypress, where the page is rendered in an iframe and we need to run our patch on a different `window`. To make this work, happo-e2e needs to expose the patch function in a way that it can be applied to a different `window`, so we are adding a window argument to the function. It defaults to `window`, so it will continue working for the current use cases just fine.
Cypress needs to call this function in its own special Cypress way, so we are adding a property to takeDOMSnapshot to make importing it easier and backwards compatible.
=> Allow applyConstructedStylesPatch to take a window argument, expose as takeDOMSnapshot.applyConstructedStylesPatch()

controller.js, takeDOMSnapshot.js
We just had a report of someone trying to use the latest happo-e2e but ending up with module parse errors:
Module parse failed: Unexpected token (21:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   } else if (element[recordedCSSSymbol]) {
|     lines = element[recordedCSSSymbol];
>   } else if (element.sheet?.cssRules) {
|     // Handle <style> or <link> elements that have a sheet property
|     lines = Array.from(element.sheet.cssRules).map((rule) => rule.cssText);
I suspect this is because they are using a node version older than v14 (when optional chaining operators were introduced). It could be that it's caused by the node.js version bundled with Cypress (they are …
=> Avoid using optional chaining operators

.eslintrc.js
I asked cursor to update the eslint config so that we catch constructs that use syntax not recognized by webpack 4.
This type of linting would have prevented an issue where one of our users ran into a parse error coming from takeDOMSnapshot related to optional chaining, `element.sheet?.cssRules`.
Fixes https://linear.app/happo/issue/HAP-274/lint-against-syntax-that-is-invalid-in-webpack-v4
=> Lint against syntax that is invalid in webpack v4

.github/workflows/automerge.yml
This will automerge dependabot PRs which will reduce the amount of time we spend maintaining this repo.
=> Add automerge GitHub workflow
